<?php
/**
 * @file
 *   Alias tools.
 */

/**
 * Implements hook_permission();
 */
function cirro_alias_permission() {
	
	return array(
		'cirro manage alias' => array(
			'title' => 'Manage Aliases',
			'description' => 'Manage entity and global aliases'
		),
	);
}

/**
 * Implements hook_menu();
 */
function cirro_alias_menu() {
	// Init
	$items = array();

	// Manage page
	$items['admin/dash/alias'] = array(
		'title' => 'Manage Aliases',
		'page callback' => 'cirro_alias_page',
		'access arguments' => array('cirro manage alias'),
		'file' => 'manage_forms.inc'
	);

	$items['admin/dash/alias/%/delete'] = array(
		'title' => 'Delete Alias',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cirro_alias_delete_form', 3),
		'access arguments' => array('cirro manage alias'),
		'file' => 'entity_forms.inc'
	);

	return $items;
}

/**
 * Implements hook_for_dash
 */
function cirro_alias_for_dash(){

	// Init add blog and moderate comments
	$path = 'admin/dash/alias';
	$txt = 'Manage Aliases';

	
	// Determine classes and IDs for link
	$attributes = array(
		'class' => 'span3 action-btn'
	);

	// Build opts array()
	$opts = array( 'attributes' => $attributes );

	// Use drupal's l() top build dynamic link
	$link = l( $txt, $path, $opts );

	// Build markup for blog section
	$html = "
		<h2>Aliases</h2>
		<div class=\"action-links\">
			$link
		</div>
	";


	// Return for dashboard
	return array(
		'content' => $html, 
		'region' => 'middle',
		'permission' => 'cirro manage alias'
	);

}

/**
 * Cleanup alias strings.
 */
function cirro_alias_cleanup($alias) {
	$alias = strtolower($alias);
	$alias = str_replace(' ', '-', $alias);
	// Get rid of any unapproved characters
	$alias = preg_replace('/[^a-zA-Z\d\.\/-]/', '', $alias);

	return $alias;
}

/**
 * Include entity forms.
 */
module_load_include('inc', 'cirro_alias', 'entity_forms');