<?php

/**
 * @file
 * The define project entities.
 */

/**
 * Implements hook_entity_info().
 *
 * @return
 *   Array of entity info arrays.
 */
function project_items_entity_info() {
	
	// Init
	$entities = array();

	// Home Page
	$entities['home_page'] = array(
		'label' => t('Home Page'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_home_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// About Page
	$entities['about_page'] = array(
		'label' => t('About Page'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_about_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Press Page
	$entities['press_page'] = array(
		'label' => t('Press Page'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_press_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Contact Page
	$entities['contact_page'] = array(
		'label' => t('Contact Page'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_contact_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Store Item
	$entities['store_item'] = array(
		'label' => t('Store Item'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_store_item',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
	
	$entities['collection'] = array(
		'label' => t('Collection'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_collection',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
	
	$entities['blog'] = array(
		'label' => t('Blog'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_blog',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
		
	$entities['location'] = array(
		'label' => t('Location'),
		'controller class' => 'cirroCoreController',
		'base table' => 'cirro_location',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table'),
	);


	
	return $entities;

}



