<?php

/**
 * @file
 * The define items entities.
 */

/**
 * Implements hook_entity_info().
 *
 * @return
 *   Array of entity info arrays.
 */
function cirro_items_entity_info() {
	
	// Init
	$entities = array();

	// Home Page
	$entities['home_page'] = array(
		'label' => t('Home Page'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_home_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// About Page
	$entities['about_page'] = array(
		'label' => t('About Page'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_about_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Press Page
	$entities['press_page'] = array(
		'label' => t('Press Page'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_press_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Contact Page
	$entities['contact_page'] = array(
		'label' => t('Contact Page'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_contact_page',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('primary'),
	);

	// Store Item
	$entities['store_item'] = array(
		'label' => t('Store Item'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_store_item',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
	
	$entities['collection'] = array(
		'label' => t('Collection'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_collection',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
	
	$entities['blog'] = array(
		'label' => t('Blog'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_blog',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table', 'weight'),
	);
		
	$entities['location'] = array(
		'label' => t('Location'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_location',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
		'dashboard' => array('add', 'table'),
	);

	$entities['multi_img'] = array(
		'label' => t('Multiple Image'),
		'controller class' => 'cirroItemsController',
		'base table' => 'cirro_multi_img',
		'fieldable' => FALSE,
		'entity keys' => array(
			'id' => 'id',
		),
		'static cache' => TRUE,
	);
	
	return $entities;

}


/*
 * Implements hook_js_alter
 *
 * Updates jQuery on all pages for the overlay plugin
 */
function cirro_items_js_alter(&$javascript) {

	global $theme;
	// Conditional so it won't run on admin pages
	if ($theme !== 'climAdmin'){
		// Define path to jQuery
		$jquery_path = '//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js';
	
		// Upgrade jQuery
		$javascript['misc/jquery.js']['data'] = $jquery_path;	
	
	}
}


/**
 * Load single entity item.
 *
 * @param $id
 *   ID of item to load
 *
 * @param $type
 *   Entity type of item to load.
 *
 * @return
 *   Item object
 */
function cirro_items_single_load($id, $type) {
	
	// Load array from entity_load
	$array = entity_load($type, array($id));
	
	// Return first item
	return reset($array);

}

